# Generated by Django 4.0.5 on 2022-07-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_brand_reviews_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
