# Generated by Django 4.0.5 on 2022-07-24 12:56

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
