# Generated by Django 4.0.5 on 2022-07-28 02:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=300)),
                ('checkout', models.BooleanField(default=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip', models.IntegerField(default=1)),
            ],
        ),
    ]
