# Generated by Django 4.0.5 on 2022-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_checkout_mobile_alter_checkout_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
